services:
  - type: web
    name: mock-api-swagger
    env: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /test
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
